language: node_js
node_js:
  - 'lts/*'

script:
  - mkdir release
  - yarn build-chrome
  - cd dist && zip -r9 ohmywish-webextension-chrome.zip * && mv *.zip ../release ; cd ..
  - yarn build-ff
  - cd dist && zip -r9 ohmywish-webextension-firefox.zip * && mv *.zip ../release ; cd ..
  - yarn build-opera
  - cd dist && zip -r9 ohmywish-webextension-opera.zip * && mv *.zip ../release ; cd ..

before_deploy:
  - mv release/ohmywish-webextension-chrome.zip release/ohmywish-webextension-chrome-${TRAVIS_TAG}.zip
  - mv release/ohmywish-webextension-firefox.zip release/ohmywish-webextension-firefox-${TRAVIS_TAG}.zip
  - mv release/ohmywish-webextension-opera.zip release/ohmywish-webextension-opera-${TRAVIS_TAG}.zip

deploy:
  - provider: releases
    api_key: $GITHUB_OAUTHKEY
    file:
      - release/ohmywish-webextension-chrome-${TRAVIS_TAG}.zip
      - release/ohmywish-webextension-firefox-${TRAVIS_TAG}.zip
      - release/ohmywish-webextension-opera-${TRAVIS_TAG}.zip
    skip_cleanup: true
    on:
      tags: true
