name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: mkdir release
      - run: yarn build-chrome
      - run: cd dist && zip -r9 ohmywish-webextension-chrome.zip * && mv *.zip ../release ; cd ..
      - run: yarn build-ff
      - run: cd dist && zip -r9 ohmywish-webextension-firefox.zip * && mv *.zip ../release ; cd ..
      - run: yarn build-opera
      - run: cd dist && zip -r9 ohmywish-webextension-opera.zip * && mv *.zip ../release ; cd ..
        env:
          CI: true
